api_platform:
    title: 'API Site BACV'
    description: 'API du club BACV pour appli mobile'
    collection:
        pagination:
            enabled: false
        #pagination_enabled: false
    show_webby: false
    version: '1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        #json: ['application/merge-patch+json']
        json: ['application/json']
    swagger:
        versions: [3]
        api_keys:
          apiKey:
            name: Authorization
            type: header