homepage:
    path: /
    controller: App\Controller\HomeController::index
authentication_token:
    path: /api/login
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh